### ISSUE TITLE
"MM" Shortcut Name is Confusing

### ISSUE THREAD

**Issue by danschmidt5189** [aanari/Test-Core#2]
This is really two issues:
1. The shortcut "MM" implies Test::MockModule, but actually uses Sub::Override, which is confusing
2. Why use Sub::Override at all? It doesn't seem to offer access to the original/unmocked subroutine (MockModule does), so it's of limited use for things like spying on arguments without altering behavior.

(2) Might just be a misunderstanding on my part - open to suggestions.

**Comment by aanari** [comment]
lgtm

**Comment by aanari** [comment]
Done, and it will be released to CPAN shortly: https://github.com/aanari/Test-Core/commit/353a71cbe053505c34e00de945ad4d85c74fc8f6
